### ISSUE TITLE
Alter grafana panel json during setup

### ISSUE THREAD

**Issue by sasha-ch** [atx/prometheus-tor_exporter#10]
To make [your grafana panel](https://gist.githubusercontent.com/atx/f4d12616eaac919b6764109ffd470c99/raw/59c9e56362b8b753e998a89aa6799dc11497e92f/grafana.json) works for other users, they need to remove your tor instance name (moridin.atx.name) from its metric names (or replace with some other).

Add this info to README or update json text for neutral version.

**Comment by atx** [comment]
Good point, I have updated the gist. It would probably be even better to use grafana variables but I don't have time for setting that up at the moment.
