### ISSUE TITLE
Wrong /etc/default settings path

### ISSUE THREAD

**Issue by simonszu** [atx/prometheus-tor_exporter#6]
I have noticed a minor error in the README, but i didn't want to fork this repo for such a minor error. 

The readme says that the configuration is in `/etc/default/prometheus-tor_exporter`. This isn't the case, this file is ignored. One must rather edit `/etc/default/prometheus-tor-exporter` (notice the dash instead the underscore).

**Comment by atx** [comment]
Fixed in 57aa8b3a6cc49ec547e33400ac36b619ed6b55d6. I also fixed URLs using my old Github username.
