### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by priegger** [atx/prometheus-tor_exporter#8]
The exporter is currently unusable for me without the stem 1.7+ compatibility fixes in commit  2b88df4c2cb2837352c8cab3ca728316f4ba303c. I'm using NixOS and have a private overlay which updates the package to the current master (which works for me).

Could you release a new version with those fixes?

**Comment by atx** [comment]
Done in [v0.4](https://github.com/atx/prometheus-tor_exporter/releases/tag/v0.4)
